# Generated by Django 4.0.2 on 2022-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermotosell',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
