# Generated by Django 4.0.2 on 2022-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0002_alter_membermotosell_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermotosell',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
