# Generated by Django 4.0.2 on 2022-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0003_alter_membermotosell_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermotosell',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='motosellmodel',
            name='Moto_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
