# Generated by Django 4.0.2 on 2022-02-28 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0004_alter_membermotosell_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermotosell',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='motosellmodel',
            name='post_Moto',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
