# Generated by Django 4.0.2 on 2022-03-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0006_alter_membermotosell_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motosellmodel',
            name='post_Moto',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
